name: Nabtrade Connect Xero Merge Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  oss-maven-workflow:
    uses: LimeMojito/oss-maven-standards/.github/workflows/oss-java-build.yml@master
    secrets: inherit
